[y, Fs] = audioread('lab_female.wav');
duration = linspace(0, length(y)/Fs, length(y));
plot(duration, y);
line([0.7 0.7], ylim, 'Linestyle', '--', 'color', 'red');
line([1.97 1.97], ylim, 'Linestyle', '--', 'color', 'red');
line([3.45 3.45], ylim, 'Linestyle', '--', 'color', 'red');
line([4.68 4.68], ylim, 'Linestyle', '--', 'color', 'red');
line([6.09 6.09], ylim, 'Linestyle', '--', 'color', 'red');
line([7.13 7.13], ylim, 'Linestyle', '--', 'color', 'red');
line([7.827 7.827], ylim, 'Linestyle', '--', 'color', 'red');
line([6.5 6.5], ylim, 'Linestyle', '--', 'color', 'red');
line([5.15 5.15], ylim, 'Linestyle', '--', 'color', 'red');
line([3.857 3.857], ylim, 'Linestyle', '--', 'color', 'red');
line([2.473 2.473], ylim, 'Linestyle', '--', 'color', 'red');
line([1.225 1.225], ylim, 'Linestyle', '--', 'color', 'red');