[y, Fs] = audioread('studio_male.wav');
duration = linspace(0, length(y)/Fs, length(y));
plot(duration,y);
line([0.7 0.7], ylim, 'Linestyle', '--', 'color', 'red');
line([3.29 3.29], ylim, 'Linestyle', '--', 'color', 'red');
line([4.82 4.82], ylim, 'Linestyle', '--', 'color', 'red');
line([6 6], ylim, 'Linestyle', '--', 'color', 'red');
line([2.973 2.973], ylim, 'Linestyle', '--', 'color', 'red');
line([4.455 4.455], ylim, 'Linestyle', '--', 'color', 'red');
line([5.725 5.725], ylim, 'Linestyle', '--', 'color', 'red');
line([7.29 7.29], ylim, 'Linestyle', '--', 'color', 'red');
